### ISSUE TITLE
"Exceeds limit" error on liquidity add

### ISSUE THREAD

**Issue by 0xlain** [0xlain/range-swap-ui#32]
There is a max amount of liquidity you are allowed to add, which we do not take into account.
If you try to add more than this amount it will throw an error and not let you send the transaction.

![image](https://user-images.githubusercontent.com/92771507/139555145-802a9d21-8553-47b3-907d-a93e2131f7f3.png)

**Comment by 0xlain** [comment]
Originally I read maxCanAdd from the contract and used that as the max value, but it lets you add more than that amount

**Comment by 0xlain** [comment]
just going to add the maxCanAdd check back in to prevent the error

still not sure why it lets you add more than the supposed "max" amount but for now this is fine

**Comment by Caranell** [comment]
> I read maxCanAdd from the contract and used that as the max value, but it lets you add more than that amount

If I understand correctly, we should compare against `maxCanAdd + amount`

Because we're precomputing maxCanAdd before operation, but totalTokens value changes inside `add` function:
`totalTokens = totalTokens.add( amount )`
which also cause recalculation of maxCanAdd

🤔 
```
function add( address token, uint amount ) external returns ( uint amount_ ) {
        amount_ = value( amount ); // do this before changing totalTokens or totalSupply

        totalTokens = totalTokens.add( amount ); // add amount to total first

        require( amount <= maxCanAdd( token ), "Exceeds limit" );

        IERC20( token ).safeTransferFrom( msg.sender, address(this), amount );
        emit Add( token, amount );

        _mint( msg.sender, amount_ );
    }
```

**Comment by 0xlain** [comment]
aha! thats probably it, gonna try it out

**Comment by 0xlain** [comment]
hmm okay so i think it gets a little more complicated.

i think we have to calculate maxCanAdd on our own, rather than read the contract, because the calculation involves the adjusted totalTokens amount

```
function maxCanAdd( address token ) public view returns ( uint ) {
  require( tokenInfo[token].accepting, "Not accepting token" );

  uint maximum = totalTokens.mul( tokenInfo[ token ].highAP ).div( 1e9 );
  uint balance = IERC20( token ).balanceOf( address(this) );

  return maximum.sub( balance );
}
```
