### ISSUE TITLE
Max calculation blocks getting tokens

### ISSUE THREAD

**Issue by Caranell** [0xlain/range-swap-ui#41]
@0xlain, I faced the issue [you were talking about](https://github.com/0xlain/range-swap-ui/pull/33#discussion_r739868073) and function to count max really can stuck in a loop for too long (I stopped test after  5000+ iterations)

<img width="497" alt="Screenshot" src="https://user-images.githubusercontent.com/9637757/139604389-924f91d2-c471-4627-a0c3-107a2f472cb5.png">

I think we probably need to review our code once more or at least call `max` function after getting necessary token' info

**Comment by 0xlain** [comment]
oh wow, my tests never got up to 5000, usually only like 100.

yeah lets look into this

**Comment by 0xlain** [comment]
I still don't know of a way to get the max without using a loop like we have currently.

we can:
1. run the loop after we get token info / run it in the background
2. cap the loop at some number or cycles, ie. 80
